from typing import Optional

from kor import create_extraction_chain
from kor import from_pydantic
from pydantic import BaseModel

from llm_loader import main as llm_loader


# Pydantic data class
class UserInfo(BaseModel):
    # Personal Identification Information
    itching: Optional[bool]
    skin_rash: Optional[bool]
    nodal_skin_eruptions: Optional[bool]
    continuous_sneezing: Optional[bool]
    shivering: Optional[bool]
    chills: Optional[bool]
    joint_pain: Optional[bool]
    stomach_pain: Optional[bool]
    acidity: Optional[bool]
    ulcers_on_tongue: Optional[bool]
    muscle_wasting: Optional[bool]
    vomiting: Optional[bool]
    burning_micturition: Optional[bool]
    spotting_urination: Optional[bool]
    fatigue: Optional[bool]
    weight_gain: Optional[bool]
    anxiety: Optional[bool]
    cold_hands_and_feets: Optional[bool]
    mood_swings: Optional[bool]
    weight_loss: Optional[bool]
    restlessness: Optional[bool]
    lethargy: Optional[bool]
    patches_in_throat: Optional[bool]
    irregular_sugar_level: Optional[bool]
    cough: Optional[bool]
    high_fever: Optional[bool]
    sunken_eyes: Optional[bool]
    breathlessness: Optional[bool]
    sweating: Optional[bool]
    dehydration: Optional[bool]
    indigestion: Optional[bool]
    headache: Optional[bool]
    yellowish_skin: Optional[bool]
    dark_urine: Optional[bool]
    nausea: Optional[bool]
    loss_of_appetite: Optional[bool]
    pain_behind_the_eyes: Optional[bool]
    back_pain: Optional[bool]
    constipation: Optional[bool]
    abdominal_pain: Optional[bool]
    diarrhoea: Optional[bool]
    mild_fever: Optional[bool]
    yellow_urine: Optional[bool]
    yellowing_of_eyes: Optional[bool]
    acute_liver_failure: Optional[bool]
    fluid_overload: Optional[bool]
    swelling_of_stomach: Optional[bool]
    swelled_lymph_nodes: Optional[bool]
    malaise: Optional[bool]
    blurred_and_distorted_vision: Optional[bool]
    phlegm: Optional[bool]
    throat_irritation: Optional[bool]
    redness_of_eyes: Optional[bool]
    sinus_pressure: Optional[bool]
    runny_nose: Optional[bool]
    congestion: Optional[bool]
    chest_pain: Optional[bool]
    weakness_in_limbs: Optional[bool]
    fast_heart_rate: Optional[bool]
    pain_during_bowel_movements: Optional[bool]
    pain_in_anal_region: Optional[bool]
    bloody_stool: Optional[bool]
    irritation_in_anus: Optional[bool]
    neck_pain: Optional[bool]
    dizziness: Optional[bool]
    cramps: Optional[bool]
    bruising: Optional[bool]
    obesity: Optional[bool]
    swollen_legs: Optional[bool]
    swollen_blood_vessels: Optional[bool]
    puffy_face_and_eyes: Optional[bool]
    enlarged_thyroid: Optional[bool]
    brittle_nails: Optional[bool]
    swollen_extremeties: Optional[bool]
    excessive_hunger: Optional[bool]
    extra_marital_contacts: Optional[bool]
    drying_and_tingling_lips: Optional[bool]
    slurred_speech: Optional[bool]
    knee_pain: Optional[bool]
    hip_joint_pain: Optional[bool]
    muscle_weakness: Optional[bool]
    stiff_neck: Optional[bool]
    swelling_joints: Optional[bool]
    movement_stiffness: Optional[bool]
    spinning_movements: Optional[bool]
    loss_of_balance: Optional[bool]
    unsteadiness: Optional[bool]
    weakness_of_one_body_side: Optional[bool]
    loss_of_smell: Optional[bool]
    bladder_discomfort: Optional[bool]
    foul_smell_ofurine: Optional[bool]
    continuous_feel_of_urine: Optional[bool]
    passage_of_gases: Optional[bool]
    internal_itching: Optional[bool]
    toxic_look_typhos: Optional[bool]
    depression: Optional[bool]
    irritability: Optional[bool]
    muscle_pain: Optional[bool]
    altered_sensorium: Optional[bool]
    red_spots_over_body: Optional[bool]
    belly_pain: Optional[bool]
    abnormal_menbooluation: Optional[bool]
    dischromic_patches: Optional[bool]
    watering_from_eyes: Optional[bool]
    increased_appetite: Optional[bool]
    polyuria: Optional[bool]
    family_history: Optional[bool]
    mucoid_sputum: Optional[bool]
    rusty_sputum: Optional[bool]
    lack_of_concentration: Optional[bool]
    visual_disturbances: Optional[bool]
    receiving_blood_transfusion: Optional[bool]
    coma: Optional[bool]
    stomach_bleeding: Optional[bool]
    distention_of_abdomen: Optional[bool]
    history_of_alcohol_consumption: Optional[bool]
    fluid_overload: Optional[bool]
    receiving_unsterile_injections: Optional[bool]
    blood_in_sputum: Optional[bool]
    prominent_veins_on_calf: Optional[bool]
    palpitations: Optional[bool]
    painful_walking: Optional[bool]
    pus_filled_pimples: Optional[bool]
    blackheads: Optional[bool]
    scurring: Optional[bool]
    red_sore_around_nose: Optional[bool]
    skin_peeling: Optional[bool]
    silver_like_dusting: Optional[bool]
    small_dents_in_nails: Optional[bool]
    inflammatory_nails: Optional[bool]
    blister: Optional[bool]
    yellow_crust_ooze: Optional[bool]
    prognosis: Optional[bool]


# open the template file
with open("Data/extraction_prompt.txt", "r") as f:
    QUERY = f.read()


def main(conversation: str):
    llm = llm_loader()
    schema, validator = from_pydantic(UserInfo)
    # Extraction
    chain = create_extraction_chain(
        llm, schema, encoder_or_encoder_class="json", validator=validator
    )
    query = f"""Please extract the patient's different syntone from this conversation.\n\n Please confirm the 
    presence of these symptoms with a Boolean (True or False).\n\n Do NOT include any additional information. The 
    output MUST follow the above scheme. Do NOT add any additional columns that are not included in the scheme.\n\n
     {conversation}"""

    return chain.run(query)["validated_data"]
