#llm:
  #name: "ollama"
  #model_name: "mistral:7b-instruct"

llm:
  name: "openai"
  openai_api_key: ${oc.env:OPENAI_API_KEY}
  openai_organization_id: ${oc.env:OPENAI_ORG}

embeddings:
  model_name: "sentence-transformers/all-mpnet-base-v2"
  device: "cpu"
  normalize_embeddings: False